language: php

php:
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: required
dist: precise

env:
  global:
    - NODE_ENV=test

addons:
  postgresql: "9.5"
services:
  - postgresql

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - cp phpunit.xml.dist  phpunit.xml
  - psql -c 'create database laravel_admin_test;' -U postgres
  - export PGPASSWORD=''; psql -U postgres -h localhost -d laravel_admin_test -f database/dump/2018-09-28.sql
  - unset PGPASSWORD
  - composer self-update
  - composer update --no-progress
  - composer install --no-progress --no-interaction

script:
  - phpunit