os:
  - linux

language: php

dist: bionic

services:
  - mysql

php:
  - "7.2"

cache:
  directories:
    - node_modules
    - vendor


env:
  global:
    - TZ: 'Europe/Moscow'
    - NODE_ENV=test
    - MYSQL_DATABASE=laravel_cms_7
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=
    - DB_HOST=127.0.0.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - cp phpunit.xml.dist  phpunit.xml
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - echo "SET GLOBAL sql_mode='';" | mysql --user="$MYSQL_USER" --password="$MYSQL_ROOT_PASSWORD" --host="$DB_HOST"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;'
  - cat storage/mysql_dump/dump.sql | mysql --user="$MYSQL_USER" --password="$MYSQL_ROOT_PASSWORD" --host="$DB_HOST" $MYSQL_DATABASE
  - composer self-update
  - composer update --no-progress
  - composer install --no-progress --no-interaction

script:
  - vendor/bin/phpunit --colors
