<?php

namespace Tests;

use Encore\Admin\Auth\Database\Administrator;
use Illuminate\Support\Facades\Session;

trait AdminTrait
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Session::start();

        $this->be(Administrator::first(), 'admin');
    }
}
