<?php

namespace Tests;

use Encore\Admin\Auth\Database\Administrator;
use Illuminate\Support\Facades\Session;

trait AdminTrait
{
    protected $user;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Session::start();

        $this->user = Administrator::query()->where('username', 'admin')->first();
        $this->be($this->user, 'admin');
    }
}
